#!/bin/bash
# Deploy Obus Website
# command line: obus_website_deploy

: 'echo "Backing up /var/aspnetcore/obus"
backupFolder=$(date +"%Y.%m.%d_%H.%M.%S")
cd ~/Documents/backup
mkdir ${backupFolder}
echo "Folder $backupFolder has been created"
echo "Copying file..."
sudo cp -r /var/aspnetcore/obus/* ~/Documents/backup/$backupFolder
'

echo "Removing files"
sudo rm -rf /var/aspnetcore/obus/*
echo "All files in /var/aspnetcore/obus/ are removed."

echo "Copy file from publish folder to /var/aspnetcore/obus/"
#sudo cp -r ~/Documents/websites/* /var/aspnetcore/obus
sudo cp -r /home/suting/Documents/Projects/obus-schedules-optimization-app/Obus.ScheduleOptimization.App/bin/release/netcoreapp2.1/ubuntu.18.04-x64/publish/* /var/aspnetcore/obus
echo "Copied website contents"

echo "Restarting supervisor..."
sudo service supervisor stop
sudo service supervisor start
echo "Supervisor restarted"

echo "Running websites..."
sudo tail -f /var/log/supervisor/supervisord.log